from fastapi import APIRouter, Depends, HTTPException, Header, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
import json
import urllib.request
import urllib.error
import re
from typing import Optional

from app import crud, models, db
from app.routers.auth import get_current_user
from app.ml.scoring import calculate_financial_health_score
from app.ml.clustering import analyze_spending_personality

router = APIRouter(
    prefix="/advisor",
    tags=["AI Financial Advisor"]
)

class ChatQuery(BaseModel):
    message: str

def query_gemini_api(api_key: str, prompt: str, system_instruction: str) -> str:
    """Calls the official Gemini API using urllib to avoid external library dependencies."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
    
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "systemInstruction": {
            "parts": [
                {"text": system_instruction}
            ]
        },
        "generationConfig": {
            "maxOutputTokens": 300,
            "temperature": 0.4
        }
    }
    
    req_data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=req_data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            # Extract text from response structure
            candidates = res_data.get("candidates", [])
            if candidates:
                text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                return text.strip()
            return "No response generated by Gemini."
    except urllib.error.HTTPError as e:
        err_msg = e.read().decode("utf-8")
        print(f"Gemini API HTTP Error: {e.code} - {err_msg}")
        return f"Gemini API Error: {e.code}. Falling back to local advisor."
    except Exception as e:
        print(f"Gemini connection error: {e}")
        return "Gemini API connection error. Falling back to local advisor."

@router.post("/chat")
def chat_with_advisor(
    query: ChatQuery,
    x_gemini_key: Optional[str] = Header(None),
    current_user: models.User = Depends(get_current_user),
    session: Session = Depends(db.get_db)
):
    user_msg = query.message.lower().strip()
    
    # 1. Gather context from DB
    transactions = crud.get_transactions(session, user_id=current_user.id, limit=200)
    budgets = crud.get_budgets(session, user_id=current_user.id)
    
    total_income = sum(tx.amount for tx in transactions if tx.type == "credit")
    total_expense = sum(tx.amount for tx in transactions if tx.type == "debit")
    balance = total_income - total_expense
    
    health_data = calculate_financial_health_score(transactions, budgets)
    personality_data = analyze_spending_personality(transactions)
    
    # Check if Gemini API key is provided
    api_key = x_gemini_key or getattr(current_user, 'gemini_api_key', None)
    
    if api_key:
        # Construct system prompt
        system_instruction = (
            "You are the AI Financial Behavior Advisor, a premium, intelligent, and supportive personal finance guide. "
            "Your goal is to offer highly personalized, actionable advice based on the user's specific financial data. "
            "Keep answers concise (under 4 sentences), friendly, and structured. Use emojis occasionally for a premium experience. "
            "Never make up numbers; only reference details from the context provided."
        )
        
        # Format transaction list for prompt
        tx_summary = []
        for tx in transactions[:15]:
            tx_summary.append(f"- {tx.date}: {tx.description} ({tx.category}) - ₹{tx.amount} [{tx.type}]")
            
        prompt = (
            f"User Profile:\n"
            f"- Personality: {personality_data.get('personality')}\n"
            f"- Financial Health Score: {health_data.get('score')}/100 (Grade: {health_data.get('grade')})\n"
            f"- Savings Score: {health_data.get('breakdown', {}).get('savings_score')}/100\n"
            f"- Overspending Risk: {health_data.get('breakdown', {}).get('overspending_risk')}/100\n"
            f"- Current Net Cash Flow: ₹{balance:.2f} (Income: ₹{total_income:.2f}, Expenses: ₹{total_expense:.2f})\n"
            f"Recent Transactions:\n"
            f"{chr(10).join(tx_summary)}\n\n"
            f"User Question: {query.message}\n"
            f"Response:"
        )
        
        gemini_response = query_gemini_api(api_key, prompt, system_instruction)
        if not gemini_response.startswith("Gemini API Error"):
            return {"response": gemini_response, "source": "gemini"}
            
    # 2. Local Fallback Rule-Based Agent
    # If no key, or if Gemini API fails, run highly tailored rules
    response = ""
    
    # Handle "afford" questions, e.g. "can I afford a ₹15000 watch?"
    afford_match = re.search(r"afford\s+(?:a\s+)?(?:[\$₹]|rs\.?|inr)?\s*([0-9,]+(?:\.[0-9]+)?)", user_msg)
    if afford_match:
        target_amount = float(afford_match.group(1).replace(",", ""))
        if target_amount > balance:
            response = (
                f"Checking your cash flow: Your current net balance is **₹{balance:.2f}**. "
                f"Purchasing this for **₹{target_amount:.2f}** would place you in a negative balance. "
                f"I recommend postponing this purchase or allocating saving milestones."
            )
        elif target_amount > balance * 0.3:
            response = (
                f"Your balance is **₹{balance:.2f}**. A purchase of **₹{target_amount:.2f}** represents "
                f"over 30% of your remaining cash flow. While technically affordable, it may affect your "
                f"savings targets. Consider waiting 48 hours before committing!"
            )
        else:
            response = (
                f"Yes! A purchase of **₹{target_amount:.2f}** fits comfortably into your current net balance "
                f"of **₹{balance:.2f}** (accounting for less than 10% of cash flow). Go ahead!"
            )
            
    # Handle "overspending" or "where do I spend"
    elif any(x in user_msg for x in ["overspend", "overspending", "where is my money", "where do i spend", "highest category"]):
        # Find category sums
        spend_by_cat = {}
        for tx in transactions:
            if tx.type == "debit":
                spend_by_cat[tx.category] = spend_by_cat.get(tx.category, 0.0) + tx.amount
        if spend_by_cat:
            top_cat = max(spend_by_cat, key=spend_by_cat.get)
            top_amount = spend_by_cat[top_cat]
            pct = (top_amount / total_expense) * 100 if total_expense > 0 else 0
            response = (
                f"Your highest spending category is **{top_cat}** at **₹{top_amount:.2f}**, which represents "
                f"**{pct:.1f}%** of your total monthly expenditures (₹{total_expense:.2f}). "
                f"Trimming your {top_cat.lower()} costs by 10% could unlock **₹{top_amount * 0.1:.2f}** in monthly savings!"
            )
        else:
            response = "I don't see any expense transactions logged. Once you log transactions, I can show you where you spend the most."
            
    # Handle "save" or "how much should I save" or "savings rate"
    elif any(x in user_msg for x in ["save", "savings", "savings rate", "how much should i save"]):
        curr_rate = health_data["breakdown"]["savings_score"]
        response = (
            f"Based on your metrics, your current Savings Rating is **{curr_rate}/100**. "
            f"The standard recommendation is to save at least **20%** of your income. "
            f"To achieve this, establish an automatic transfer on paycheck day and adjust your Leisure budgets."
        )
        
    # Handle "personality" or "spending style"
    elif any(x in user_msg for x in ["personality", "style", "behavior", "who am i", "grouping"]):
        response = (
            f"Your current Spending Personality is classified as a **{personality_data.get('personality')}**. "
            f"This is determined by analyzing your category distributions and savings rate. "
            f"You can view your detailed behavioral radar graph on the **Analytics** page."
        )
        
    # Handle "health" or "financial health" or "score"
    elif any(x in user_msg for x in ["health", "health score", "grade", "score"]):
        breakdown = health_data["breakdown"]
        response = (
            f"Your Financial Health Score is **{health_data['score']}/100** (Grade: **{health_data['grade']}**). "
            f"Here is your breakdown: Savings: **{breakdown['savings_score']}**, "
            f"Budgeting: **{breakdown['budgeting_efficiency']}**, Debt Risk: **{breakdown['debt_risk']}**, "
            f"Overspending Risk: **{breakdown['overspending_risk']}**. Check the **Analytics** tab to read personalized steps."
        )
        
    # General greetings or fallback
    else:
        response = (
            f"Hello! I am your AI Financial Behavior Advisor. 🧠\n\n"
            f"Based on your profile, you have a **{health_data['score']}/100** Financial Health Score and a "
            f"**{personality_data.get('personality')}** spending style. You can ask me questions like:\n"
            f"- *'Can I afford a ₹15,000 purchase?'*\n"
            f"- *'Where am I overspending?'*\n"
            f"- *'Tell me about my spending personality.'*\n\n"
            f"*Tip: Input your own Gemini API Key in the Settings page to unlock standard LLM generation capabilities!*"
        )
        
    return {"response": response, "source": "local"}
